service: snaplock

provider:
  name: aws
  runtime: go1.x
  environment:
        TABLE_NAME: rooms-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:

  get:
    handler: bin/get
    events:
      - http:
          path: rooms/{id}
          method: get
  post:
    handler: bin/post
    events:
      - http:
          path: rooms
          method: post
  delete:
    handler: bin/delete
    events:
      - http:
          path: rooms/{id}
          method: delete
  put:
    handler: bin/put
    events:
      - http:
          path: rooms
          method: put

resources:
  Resources:
    GoCrudDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: url
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'rooms-${opt:stage, self:provider.stage}'
